export const tradesTeams = [
  {
    id: 16,
    name: "Titans",
    adp: null,
    index: 17,
    logo: "https://api.nfldraftfanatics.com/media/ten.png",
    selection: 1,
  },
  {
    id: 27,
    name: "Rams",
    adp: null,
    index: 28,
    logo: "https://api.nfldraftfanatics.com/media/lar.png",
    selection: 2,
  },
  {
    id: 28,
    name: "Packers",
    adp: null,
    index: 29,
    logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
    selection: 3,
  },
  {
    id: 32,
    name: "Commanders",
    adp: null,
    index: 11,
    logo: "https://api.nfldraftfanatics.com/media/wsh_5TI9IsB.png",
    selection: 4,
  },
  {
    id: 12,
    name: "Vikings",
    adp: null,
    index: 13,
    logo: "https://api.nfldraftfanatics.com/media/min.png",
    selection: 5,
  },
  {
    id: 24,
    name: "Colts",
    adp: null,
    index: 25,
    logo: "https://api.nfldraftfanatics.com/media/ind.png",
    selection: 6,
  },
  {
    id: 20,
    name: "Cardinals",
    adp: null,
    index: 21,
    logo: "https://api.nfldraftfanatics.com/media/ari.png",
    selection: 7,
  },
  {
    id: 21,
    name: "Broncos",
    adp: null,
    index: 22,
    logo: "https://api.nfldraftfanatics.com/media/den.png",
    selection: 8,
  },
  {
    id: 13,
    name: "Saints",
    adp: null,
    index: 14,
    logo: "https://api.nfldraftfanatics.com/media/no.png",
    selection: 9,
  },
  {
    id: 30,
    name: "Buccaneers",
    adp: 15,
    index: 31,
    logo: "https://api.nfldraftfanatics.com/media/tb.png",
    selection: 10,
  },
  {
    id: 2,
    name: "Texans",
    adp: null,
    index: 2,
    logo: "https://api.nfldraftfanatics.com/media/hou.png",
    selection: 11,
  },
  {
    id: 8,
    name: "Bears",
    adp: 1,
    index: 8,
    logo: "https://api.nfldraftfanatics.com/media/chi.png",
    selection: 12,
  },
  {
    id: 14,
    name: "Raiders",
    adp: null,
    index: 15,
    logo: "https://api.nfldraftfanatics.com/media/lv.png",
    selection: 13,
  },
  {
    id: 22,
    name: "Chargers",
    adp: null,
    index: 23,
    logo: "https://api.nfldraftfanatics.com/media/lac.png",
    selection: 14,
  },
  {
    id: 33,
    name: "Dolphins",
    adp: 12,
    index: 10,
    logo: "https://api.nfldraftfanatics.com/media/MIA.png",
    selection: 15,
  },
  {
    id: 1,
    name: "Falcons",
    adp: null,
    index: 1,
    logo: "https://api.nfldraftfanatics.com/media/atl_1.png",
    selection: 16,
  },
  {
    id: 7,
    name: "Panthers",
    adp: null,
    index: 7,
    logo: "https://api.nfldraftfanatics.com/media/car.png",
    selection: 17,
  },
  {
    id: 17,
    name: "Browns",
    adp: null,
    index: 18,
    logo: "https://api.nfldraftfanatics.com/media/cle.png",
    selection: 18,
  },
  {
    id: 15,
    name: "Patriots",
    adp: null,
    index: 16,
    logo: "https://api.nfldraftfanatics.com/media/ne.png",
    selection: 19,
  },
  {
    id: 11,
    name: "Steelers",
    adp: null,
    index: 12,
    logo: "https://api.nfldraftfanatics.com/media/pit.png",
    selection: 20,
  },
  {
    id: 5,
    name: "Jets",
    adp: null,
    index: 5,
    logo: "https://api.nfldraftfanatics.com/media/nyj.png",
    selection: 21,
  },
  {
    id: 4,
    name: "Seahawks",
    adp: null,
    index: 4,
    logo: "https://api.nfldraftfanatics.com/media/sea.png",
    selection: 22,
  },
  {
    id: 19,
    name: "Ravens",
    adp: null,
    index: 20,
    logo: "https://api.nfldraftfanatics.com/media/bal.png",
    selection: 23,
  },
  {
    id: 6,
    name: "Jaguars",
    adp: null,
    index: 6,
    logo: "https://api.nfldraftfanatics.com/media/jax.png",
    selection: 24,
  },
  {
    id: 9,
    name: "Giants",
    adp: null,
    index: 9,
    logo: "https://api.nfldraftfanatics.com/media/nyg.png",
    selection: 25,
  },
  {
    id: 25,
    name: "Cowboys",
    adp: null,
    index: 26,
    logo: "https://api.nfldraftfanatics.com/media/dal.png",
    selection: 26,
  },
  {
    id: 31,
    name: "Bills",
    adp: null,
    index: 32,
    logo: "https://api.nfldraftfanatics.com/media/buf.png",
    selection: 27,
  },
  {
    id: 3,
    name: "Lions",
    adp: null,
    index: 3,
    logo: "https://api.nfldraftfanatics.com/media/det.png",
    selection: 28,
  },
  {
    id: 26,
    name: "Bengals",
    adp: null,
    index: 27,
    logo: "https://api.nfldraftfanatics.com/media/cin.png",
    selection: 29,
  },
  {
    id: 23,
    name: "49ers",
    adp: null,
    index: 24,
    logo: "https://api.nfldraftfanatics.com/media/sf.png",
    selection: 30,
  },
  {
    id: 18,
    name: "Eagles",
    adp: null,
    index: 19,
    logo: "https://api.nfldraftfanatics.com/media/phi.png",
    selection: 31,
  },
  {
    id: 29,
    name: "Chiefs",
    adp: null,
    index: 30,
    logo: "https://api.nfldraftfanatics.com/media/kc.png",
    selection: 32,
  },
];

export const team = {
  id: 28,
  name: "Packers",
  adp: null,
  index: 29,
  logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
  selection: 3,
  picks: [
    {
      pick: 3,
      value: "514.0",
      index: 3,
    },
    {
      pick: 3,
      value: "170.0",
      index: 35,
    },
    {
      pick: 3,
      value: "75.0",
      index: 67,
    },
    {
      pick: 3,
      value: "34.575",
      index: 104,
    },
    {
      pick: 3,
      value: "16.975",
      index: 140,
    },
    {
      pick: 40,
      value: "5.875",
      index: 177,
    },
    {
      pick: 3,
      value: "5.417",
      index: 180,
    },
    {
      pick: 39,
      value: "2.573",
      index: 216,
    },
    {
      pick: 40,
      value: "2.494",
      index: 217,
    },
    {
      pick: 3,
      value: "1.99",
      index: 224,
    },
  ],
  picksYears: [
    {
      round: "R1",
      id: 3115,
      value: "514.0",
    },
    {
      round: "R2",
      id: 3147,
      value: "170.0",
    },
    {
      round: "R3",
      id: 3179,
      value: "75.0",
    },
    {
      round: "R4",
      id: 3216,
      value: "34.575",
    },
    {
      round: "R5",
      id: 3252,
      value: "16.975",
    },
    {
      round: "R5",
      id: 3289,
      value: "5.875",
    },
    {
      round: "R6",
      id: 3292,
      value: "5.417",
    },
    {
      round: "R6",
      id: 3328,
      value: "2.573",
    },
    {
      round: "R6",
      id: 3329,
      value: "2.494",
    },
    {
      round: "R7",
      id: 3336,
      value: "1.99",
    },
  ],
  pick: [],
  pickYear: [],
  players: [
    {
      player: "Select Players",
      position: "",
    },
    {
      id: 1302,
      value: 5003,
      position: "QB",
      player: "Aaron Rodgers",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1303,
      value: 26,
      position: "LT",
      player: "David Bakhtiari",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1304,
      value: 26,
      position: "DT",
      player: "Kenny Clark",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1305,
      value: 553,
      position: "CB",
      player: "Jaire Alexander",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1306,
      value: 103,
      position: "RB",
      player: "Aaron Jones",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1307,
      value: 26,
      position: "OLB",
      player: "Preston Smith",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1308,
      value: 103,
      position: "OLB",
      player: "Rashan Gary",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1309,
      value: 26,
      position: "ILB",
      player: "De'Vondre Campbell",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1310,
      value: 26,
      position: "FS",
      player: "Adrian Amos",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1311,
      value: 26,
      position: "SS",
      player: "Darnell Savage",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1312,
      value: 26,
      position: "CB",
      player: "Rasul Douglas",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1313,
      value: 26,
      position: "G",
      player: "Elgton Jenkins",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1314,
      value: 103,
      position: "QB",
      player: "Jordan Love",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1315,
      value: 26,
      position: "CB",
      player: "Eric Stokes",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1316,
      value: 303,
      position: "ILB",
      player: "Quay Walker",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1317,
      value: 26,
      position: "DE",
      player: "Dean Lowry",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1318,
      value: 403,
      position: "DT",
      player: "Devonte Wyatt",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
    {
      id: 1319,
      value: 26,
      position: "G",
      player: "Jon Runyan",
      round: {
        id: 28,
        name: "Packers",
        adp: null,
        index: 29,
        logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
      },
    },
  ],
  player: [],
};

export const teamSelect = [
  {
    id: 28,
    name: "Packers",
    adp: null,
    index: 29,
    logo: "https://api.nfldraftfanatics.com/media/gb_1.png",
    selection: 3,
  },
];